In [5]:
import pandas as pd

In [6]:
data=pd.read_csv("ex1data1.txt",names=["population","profit"])
#pd.read_csv(filepath, sep=',', names=None, header='infer')
# filepath: 文件路径字符串。
# sep: 分隔符，默认为逗号 ,。
# names: 列表，如果原文件没表头，在这里手动传列名。
# header: 整数，指定哪一行作为表头。如果没有表头，设为 None。

data.head()

   population   profit
0      6.1101  17.5920
1      5.5277   9.1302
2      8.5186  13.6620
3      7.0032  11.8540
4      5.8598   6.8233

In [7]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 97 entries, 0 to 96
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   population  97 non-null     float64
 1   profit      97 non-null     float64
dtypes: float64(2)
memory usage: 1.6 KB

In [8]:
data.tail()

    population   profit
92      5.8707  7.20290
93      5.3054  1.98690
94      8.2934  0.14454
95     13.3940  9.05510
96      5.4369  0.61705

In [9]:
data.shape

(97, 2)

In [10]:
data.describe

<bound method NDFrame.describe of     population    profit
0       6.1101  17.59200
1       5.5277   9.13020
2       8.5186  13.66200
3       7.0032  11.85400
4       5.8598   6.82330
..         ...       ...
92      5.8707   7.20290
93      5.3054   1.98690
94      8.2934   0.14454
95     13.3940   9.05510
96      5.4369   0.61705

[97 rows x 2 columns]>

In [11]:
# 1. 直接创建一个名为 'ones' 的新列，并赋值为 1
# Pandas 会自动进行“广播”，把这一列 97 行全部填满 1
data.insert(0, 'ones', 1) 

# 2. 现在查看 data.head()，你会发现第一列变成了 ones
print(data.head())
#data.insert(位置, 列名, 数值)

   ones  population   profit
0     1      6.1101  17.5920
1     1      5.5277   9.1302
2     1      8.5186  13.6620
3     1      7.0032  11.8540
4     1      5.8598   6.8233

In [14]:
data_iloc=data.iloc[:,-1:]
#df.iloc[row_index, column_index]
# 若是:则是填入所有的数据
# 若是填入一个数字取出为一维数组，无法进行向量运算，要加上一个:(例如-1:就是取出最后一行变成一个n*1的矩阵)
# 想要取出剩一行则是:+要去掉的那一行
# 若是想要取出从哪一行到另一行则是，形似0:5这样开始加上结尾的形式
data_iloc.head()

    profit
0  17.5920
1   9.1302
2  13.6620
3  11.8540
4   6.8233

In [15]:
data.dropna(axis=0,how='any',subset=None)
# #df.dropna(axis=0, how='any', subset=None)清空不当数据
# axis: 0 表示删行，1 表示删列。
# how: 'any' 表示只要有一个空值就删，'all' 表示全为空才删。
data.head()

   ones  population   profit
0     1      6.1101  17.5920
1     1      5.5277   9.1302
2     1      8.5186  13.6620
3     1      7.0032  11.8540
4     1      5.8598   6.8233

In [16]:
data.describe()# 描述数据
#df.describe(percentiles=None, include=None)
# include: 'all' 会包含非数值列，默认只看数值列。

       ones  population     profit
count  97.0   97.000000  97.000000
mean    1.0    8.159800   5.839135
std     0.0    3.869884   5.510262
min     1.0    5.026900  -2.680700
25%     1.0    5.707700   1.986900
50%     1.0    6.589400   4.562300
75%     1.0    8.578100   7.046700
max     1.0   22.203000  24.147000

In [17]:
data_np=data.values# 将pandas中的数据取出变成numpy中的数据
print(data_np)

[[ 1.       6.1101  17.592  ]
 [ 1.       5.5277   9.1302 ]
 [ 1.       8.5186  13.662  ]
 [ 1.       7.0032  11.854  ]
 [ 1.       5.8598   6.8233 ]
 [ 1.       8.3829  11.886  ]
 [ 1.       7.4764   4.3483 ]
 [ 1.       8.5781  12.     ]
 [ 1.       6.4862   6.5987 ]
 [ 1.       5.0546   3.8166 ]
 [ 1.       5.7107   3.2522 ]
 [ 1.      14.164   15.505  ]
 [ 1.       5.734    3.1551 ]
 [ 1.       8.4084   7.2258 ]
 [ 1.       5.6407   0.71618]
 [ 1.       5.3794   3.5129 ]
 [ 1.       6.3654   5.3048 ]
 [ 1.       5.1301   0.56077]
 [ 1.       6.4296   3.6518 ]
 [ 1.       7.0708   5.3893 ]
 [ 1.       6.1891   3.1386 ]
 [ 1.      20.27    21.767  ]
 [ 1.       5.4901   4.263  ]
 [ 1.       6.3261   5.1875 ]
 [ 1.       5.5649   3.0825 ]
 [ 1.      18.945   22.638  ]
 [ 1.      12.828   13.501  ]
 [ 1.      10.957    7.0467 ]
 [ 1.      13.176   14.692  ]
 [ 1.      22.203   24.147  ]
 [ 1.       5.2524  -1.22   ]
 [ 1.       6.5894   5.9966 ]
 [ 1.       9.2482  12.134  ]
 [ 1.       5.8918   1.8495 ]
 [ 1.       8.2111   6.5426 ]
 [ 1.       7.9334   4.5623 ]
 [ 1.       8.0959   4.1164 ]
 [ 1.       5.6063   3.3928 ]
 [ 1.      12.836   10.117  ]
 [ 1.       6.3534   5.4974 ]
 [ 1.       5.4069   0.55657]
 [ 1.       6.8825   3.9115 ]
 [ 1.      11.708    5.3854 ]
 [ 1.       5.7737   2.4406 ]
 [ 1.       7.8247   6.7318 ]
 [ 1.       7.0931   1.0463 ]
 [ 1.       5.0702   5.1337 ]
 [ 1.       5.8014   1.844  ]
 [ 1.      11.7      8.0043 ]
 [ 1.       5.5416   1.0179 ]
 [ 1.       7.5402   6.7504 ]
 [ 1.       5.3077   1.8396 ]
 [ 1.       7.4239   4.2885 ]
 [ 1.       7.6031   4.9981 ]
 [ 1.       6.3328   1.4233 ]
 [ 1.       6.3589  -1.4211 ]
 [ 1.       6.2742   2.4756 ]
 [ 1.       5.6397   4.6042 ]
 [ 1.       9.3102   3.9624 ]
 [ 1.       9.4536   5.4141 ]
 [ 1.       8.8254   5.1694 ]
 [ 1.       5.1793  -0.74279]
 [ 1.      21.279   17.929  ]
 [ 1.      14.908   12.054  ]
 [ 1.      18.959   17.054  ]
 [ 1.       7.2182   4.8852 ]
 [ 1.       8.2951   5.7442 ]
 [ 1.      10.236    7.7754 ]
 [ 1.       5.4994   1.0173 ]
 [ 1.      20.341   20.992  ]
 [ 1.      10.136    6.6799 ]
 [ 1.       7.3345   4.0259 ]
 [ 1.       6.0062   1.2784 ]
 [ 1.       7.2259   3.3411 ]
 [ 1.       5.0269  -2.6807 ]
 [ 1.       6.5479   0.29678]
 [ 1.       7.5386   3.8845 ]
 [ 1.       5.0365   5.7014 ]
 [ 1.      10.274    6.7526 ]
 [ 1.       5.1077   2.0576 ]
 [ 1.       5.7292   0.47953]
 [ 1.       5.1884   0.20421]
 [ 1.       6.3557   0.67861]
 [ 1.       9.7687   7.5435 ]
 [ 1.       6.5159   5.3436 ]
 [ 1.       8.5172   4.2415 ]
 [ 1.       9.1802   6.7981 ]
 [ 1.       6.002    0.92695]
 [ 1.       5.5204   0.152  ]
 [ 1.       5.0594   2.8214 ]
 [ 1.       5.7077   1.8451 ]
 [ 1.       7.6366   4.2959 ]
 [ 1.       5.8707   7.2029 ]
 [ 1.       5.3054   1.9869 ]
 [ 1.       8.2934   0.14454]
 [ 1.      13.394    9.0551 ]
 [ 1.       5.4369   0.61705]]

In [24]:
data1=data.iloc[0:5,:]
print(data1)
data2=data.iloc[5:10,:]
print(data2)
 data_concat1=pd.concat([data1,data2],axis=0)# 0是加上行
 data_concat1.head(10)
data_concat2=pd.concat([data1,data2],axis=1)# 1是列相加
data_concat2.head(10)
#pd.concat([df1, df2], axis=0)

   ones  population   profit
0     1      6.1101  17.5920
1     1      5.5277   9.1302
2     1      8.5186  13.6620
3     1      7.0032  11.8540
4     1      5.8598   6.8233
   ones  population   profit
5     1      8.3829  11.8860
6     1      7.4764   4.3483
7     1      8.5781  12.0000
8     1      6.4862   6.5987
9     1      5.0546   3.8166

   ones  population   profit  ones  population   profit
0   1.0      6.1101  17.5920   NaN         NaN      NaN
1   1.0      5.5277   9.1302   NaN         NaN      NaN
2   1.0      8.5186  13.6620   NaN         NaN      NaN
3   1.0      7.0032  11.8540   NaN         NaN      NaN
4   1.0      5.8598   6.8233   NaN         NaN      NaN
5   NaN         NaN      NaN   1.0      8.3829  11.8860
6   NaN         NaN      NaN   1.0      7.4764   4.3483
7   NaN         NaN      NaN   1.0      8.5781  12.0000
8   NaN         NaN      NaN   1.0      6.4862   6.5987
9   NaN         NaN      NaN   1.0      5.0546   3.8166